#!/bin/bash

## PROBLEM 5: Create an array for odd numbers from 1 to 50. Find the sum. Do the same for even numers





declare -a evenArr 
counter=0
sum=0

#use a for loop to fill the evenArr
for ((i=0; i<51; i+=2))
do
	evenArr[counter]=$i
	let sum+=i
	let counter+=1
done

echo "The summation of even numbers from 1 - 50: "
echo "$sum"


#use a for loop to fill the evenArr
declare -a oddArr
oddCounter=0
oddSum=0

for ((i=1; i<50; i+=2))
do 
	oddArr[evenCounter]=$i
	let oddSum+=i
	let oddCounter+=1
done 
echo "Summation of oddNumbers from 1 - 50"
echo "$oddSum"











































